dist: bionic
language: python
python:
  - 3.6
# No emails!
notifications:
  email: false
# arc bindings are not available in pip so have to install via apt and
# force the virtualenv to use system packages
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -y nordugrid-arc-python
install:
  - pip install -r requirements.txt
script:
  - pylint --extension-pkg-whitelist=htcondor,classad --errors-only src/act
