dist: bionic
language: python
python:
  - 3.6
# No emails!
notifications:
  email: false
# arc bindings are not available in pip so have to install via apt and
# force the virtualenv to use system packages
virtualenv:
  system_site_packages: true
# Install ARC 6 python3 bindings from nordugrid repo (not available in standard repo)
addons:
  apt:
    sources:
      - sourceline: 'deb https://download.nordugrid.org/repos/6/ubuntu bionic main'
      - sourceline: 'deb https://download.nordugrid.org/repos/6/ubuntu bionic-updates main'
        keyurl: https://download.nordugrid.org/DEB-GPG-KEY-nordugrid-6.asc
    packages:
      - python3-nordugrid-arc
install:
  - pip install -r requirements.txt
  - pip install rucio-clients
script:
  - pylint --extension-pkg-whitelist=htcondor,classad --errors-only src/act
